version: "3"
tasks:
  prepublish-to-local-mirror:
    desc: copy from __localbuild__/docs/site to relrepos/yairdar.github.io/aguide/latest
    vars:       
      site_dir: '$(yq eval .site_dir ./mkdocs.yml)'
      pub_dir: relrepos/yairdar.github.io/aguide
    cmds:
      # - task repo='"yairdar.github.io"' reposet:resolve:one reposet:pull:one 
      # - rm -rf relrepos/yairdar.github.io/aguide
      - rclone copy {{.site_dir}} {{.pub_dir}}

  publish-from-local-to-remote:
    desc: publish (git push) from local repo to remote
    cmds:
      - task -d relrepos/yairdar.github.io git:publish-changes
       
